config/routes.rb
Rails.application.routes.draw do
  
  get 'taggers/new'

  get 'tags/new'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  get '/signup', to: "users#new"
  
  get "/about", to: "static_pages#about"
  get '/help', to: "static_pages#help"
  get '/contact', to: "static_pages#contact"

  root "static_pages#home"
  
  resources :users do
    member do
      get :clips, :albums
    end
  end
  resources :microposts, only: [:create, :update, :destroy, :edit]
  resources :clips, only: [:create, :update, :edit, :destroy, :show, :new]
  resources :albums, only: [:create, :update, :edit, :destroy, :show, :new]
  resources :affections, only: [:create, :update, :destroy]
  resources :tags, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :taggers, only: [:create, :destroy]
  resources :searches, only: [:new, :show, :create]
  
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :microposts, dependent: :destroy
    has_many :clips, as: :owner, dependent: :destroy
    has_many :albums, dependent: :destroy
    has_many :affections, dependent: :destroy
    attr_accessor :remember_token
    #need self on the left side (email=email.downcase would 
        #create a new variable); on the right side not necessary
    before_save { self.email=email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
       SecureRandom.urlsafe_base64 
    end
    
    def remember
       self.remember_token=User.new_token
       update_attribute(:remember_digest, User.digest(remember_token)) 
    end
    
    def authenticated?(remember_token)
    return false if remember_digest.nil?
       BCrypt::Password.new(remember_digest).is_password?(remember_token) 
    end
    
    def forget
        update_attribute(:remember_digest, nil)
    end
    
    def feed
        Micropost.where("user_id=?", id)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def new
    @user=User.new
  end
  
  def clips
    unless album_to_display.nil?
      album_end_display
      clip_end_display
    end
    @user=User.find(params[:id])
    @clips=@user.clips.paginate(page: params[:page], per_page: 5)
    render "users/show_clips"
  end
  
  def albums
    @album=Album.new
    @user=User.find(params[:id])
    @albums=@user.albums.paginate(page: params[:page], per_page: 5)
    unless album_to_display.nil?
      @tags=Album.find(album_to_display).tags
      @album_display=Album.find_by(id: album_to_display)
      @clips=@album_display.clips
      create_playlist(@clips)
    end
    respond_to do |format|
      format.html { render "users/show_albums" }
      format.js { toggle_autoplay }
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success]="User deleted"
    redirect_to users_url
  end
  
  def index
    @users=User.paginate(page: params[:page])
  end
  
  def show
    @user=User.find(params[:id])
    @microposts=@user.microposts.paginate(page: params[:page])
  end
  
  def create
    @user=User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success]="Account created"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user=User.find(params[:id])
  end
  
  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_edit_params)
      flash[:success]="Profile updated"
      redirect_to @user
    else
      render "edit"
    end
  end
  
private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_conformation)
  end
  
  def user_edit_params
    params.require(:user).permit(:name, :email)
  end
  
## before filters ##
  
  def correct_user
    @user=User.find(params[:id])
    unless current_user?(@user)
      flash[:danger]="You have not the autorization to perform this action"
      redirect_to root_url
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
    
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <% if logged_in? %>
    <%= link_to user.name, user %> | 
    <% end %>
    <%= link_to user.name+"'s clips", clips_user_path(user) %>
    <% if logged_in? && current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
</li>

app/views/users/albums.js.erb
$("span.autoplay_buttons").empty();
$("span.autoplay_buttons").append("<%= j render "shared/autoplay_buttons" %>");

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>

<h1>Update your profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
            
            <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
        
        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users")%>

<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
            
            <%= f.label :password %>
            <%= f.text_field :password, class: "form-control" %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.text_field :password_confirmation, class: "form-control" %>
            
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
    <div class="col-md-8">
        <% if @user.microposts.any? %>
            <h3>Microposts (<%= @user.microposts.count %>)</h3>
            <ol class="microposts">
                <%= render @microposts %>
            </ol>
            <%= will_paginate @microposts %>
        <% end %>
    </div>
</div>

app/views/users/show_albums.html.erb
<% provide(:title, @user.name+"'s albums") %>
<div class="row">
    <aside class="col-md-8">
            <% unless album_to_display.nil? %>
                <section>
                    <h1 class="album_title"><%= Album.find(album_to_display).title %></h1>
                    <div class="col-md-1">
                        <%= render "shared/like_dislike" %>
                    </div>
                    <div class="col-md-11">
                        <%= render partial: "shared/likes", locals: {list: false} %>
                    </div>
                </section>
            <% end %>
        <section class="video_display">
            <% if album_to_display.nil? %>
                <%= render "shared/default_clip" %>
            <% else %>
                <%= render "shared/active_video" %>
                <%= render "shared/user_info" %>
                <%= render "shared/add_tag" %>
            <% end %>
        </section>
    </aside>
    <% if @user.albums.any? %>
        <div class="col-md-4">
            <%= link_to "Create an Album", new_album_path %>
            <ol class="albums">
                <%= render @albums %>
            </ol>
            <%= will_paginate @albums %>
        </div>
    <% end %>
</div>

app/views/users/show_clips.html.erb
<% provide(:title, @user.name+"'s clips") %>
<div class="row">
    <aside class="col-md-8">
        <section class="user_info">
            <h1>
                <%= render "shared/user_info" %>
            </h1>
        </section>
        <% if clip_to_display.nil? %>
            <%= render "shared/default_clip" %>
        <% else %>
            <%= render "shared/active_video" %>
        <% end %>
    </aside>
    <div class="col-md-4">
        <li><%= link_to "Add a clip", new_clip_path %></li>
        <% if @user.clips.any? %>
            <ol class="clips">
                <% @clips.each do |clip| %>
                    <%= render clip, owner: clip.owner %>
                <% end %>
                <!--render @clips, owner: clip.owner will not work here -->
            </ol>
            <%= will_paginate @clips %>
        <% end %>
    </div>
</div>