config/routes.rb
Rails.application.routes.draw do
  
  get 'taggers/new'

  get 'tags/new'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  get '/signup', to: "users#new"
  
  get "/about", to: "static_pages#about"
  get '/help', to: "static_pages#help"
  get '/contact', to: "static_pages#contact"

  root "static_pages#home"
  
  resources :users do
    member do
      get :clips, :albums
    end
  end
  resources :microposts, only: [:create, :update, :destroy, :edit]
  resources :clips, only: [:create, :update, :edit, :destroy, :show, :new]
  resources :albums, only: [:create, :update, :edit, :destroy, :show, :new]
  resources :affections, only: [:create, :update, :destroy]
  resources :tags, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :taggers, only: [:create, :destroy]
  resources :searches, only: [:new, :show, :create]
  
end

app/views/shared/_active_video.html.erb
<section class="clip">
    <%= render "clips/clip_display" %>
</section>
<% if current_page?(albums_user_path) %>
    <nav class="navbar navbar-inverse navbar-fixed-bottom scroll" id="album_navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <ul><%= link_to "Add a clip", new_clip_path %></ul>
            </div>
                <ul class="nav navbar-nav" id="album_content">
                    <!-- render @clips, owner: clip.owner.user will not work here -->
                    <% @clips.each do |clip| %>
                        <%= render clip, owner: clip.owner.user %>
                    <% end %>
                </ul>
        </div>
    </nav>
<% end %>

app/views/shared/_add_tag.html.erb
<p><%= link_to "Add a tag", "#", id: "add-tag-link" %></p>
<span id="tag-form">
    <div class="tag_adding">
        <%= form_for(Album.find(album_to_display).taggers.build) do |f| %>
        
            <%= label_tag :tag_id, "tag name" %>
            <%= text_field_tag :tag_id, "your tag", id:"field_tag", class: "form-control" %>
            
            <%= f.submit "Add tag", class:"btn btn-primary" %>
        <% end %>
    </div>
</span>

app/views/shared/_autoplay_buttons.html.erb
<% if cookies[:autoplay]=="yes" %>
    <div class="btn-group">
        <a type="button" class="btn btn-info", href='/users/<%= Album.find(album_to_display).user.id %>/albums', data-remote="true" id='autoplay-link', onclick="autoplay_stop()">Play</a>
        <a type="button" class="btn btn-default", href='/users/<%= Album.find(album_to_display).user.id %>/albums', data-remote="true" id='autoplay-link', onclick="autoplay_stop()">Stop</a>
    </div>
<% else %>
    <div class="btn-group">
        <a type="button" class="btn btn-default", href='/users/<%= Album.find(album_to_display).user.id %>/albums', data-remote="true" id='autoplay-link', onclick="autoplay_play()">Play</a>
        <a type="button" class="btn btn-info", href='/users/<%= Album.find(album_to_display).user.id %>/albums', data-remote="true" id='autoplay-link', onclick="autoplay_play()">Stop</a>
    </div>
<% end %>

app/views/shared/_default_clip.html.erb
<section class="clip">
    <iframe width="560" height="315" src="//www.youtube.com/embed/DokUjuZmpCE" frameborder="0" allowfullscreen></iframe>
</section>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error") %>
        </div>
        <ul>
            <% object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_like_dislike.html.erb
<span class="relation_buttons">
    <% if relation=current_user.affections.find_by(album_id: album_to_display) and relation.value==1 %>
        <div class="btn-group">
                <%= form_for(current_user.affections.find_by(album_id: album_to_display),
                    html: {method: :delete}, remote: true) do |f| %>
                    <%= f.submit "Like", class:"btn-success", id:"dislike_button" %>
                <% end %>
                <%= form_for(current_user.affections.find_by(album_id: album_to_display),
                    html: {method: :patch}, remote: true) do |f| %>
                    <div><%= hidden_field_tag :value, -1 %></div>
                    <%= f.submit "Dislike", class:"btn-default", id:"dislike_button" %>
                <% end %>
        </div>
    <% elsif relation=current_user.affections.find_by(album_id: album_to_display) and relation.value==-1 %>
        <div class="btn-group">
                <%= form_for(current_user.affections.find_by(album_id: album_to_display),
                    html: {method: :patch}, remote: true) do |f| %>
                    <div><%= hidden_field_tag :value, 1 %></div>
                    <%= f.submit "Like", class:"btn-default", id:"dislike_button" %>
                <% end %>
                <%= form_for(current_user.affections.find_by(album_id: album_to_display),
                    html: {method: :delete}, remote: true) do |f| %>
                    <%= f.submit "Dislike", class:"btn-danger", id:"dislike_button" %>
                <% end %>
        </div>
    <% else %>
            <div class="btn-group">
                <%= form_for(current_user.affections.build, remote: true) do |f| %>
                    <div><%= hidden_field_tag :album_id, album_to_display %></div>
                    <div><%= hidden_field_tag :value, 1 %></div>
                    <%= f.submit "Like", class:"btn-default", id:"dislike_button" %>
                <% end %>
                <%= form_for(current_user.affections.build, remote: true) do |f| %>
                    <div><%= hidden_field_tag :album_id, album_to_display %></div>
                    <div><%= hidden_field_tag :value, -1 %></div>
                    <%= f.submit "Dislike", class:"btn-default", id:"dislike_button" %>
                <% end %>
            </div>
    <% end %>
</span>

app/views/shared/_likes.html.erb
<% unless list %>
    <div class="clip_likes">
        <%= pluralize(Album.find(album_to_display).affections.where(value: 1).count, "like") %> | 
        <%= pluralize(Album.find(album_to_display).affections.where(value: -1).count, "dislike") %>
    </div>
<% else %>
    <div class="album_likes">
        <ul>
            <li><%= pluralize(Album.find(album_to_display).affections.where(value: 1).count, "like") %></li>
            <li><%= pluralize(Album.find(album_to_display).affections.where(value: -1).count, "dislike") %></li>
        </ul>
    </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose a new post" %>
    </div>
    <% if post_to_edit.nil? %>
        <%= f.submit "Post", class: "btn btn-primary" %>
    <% else %>
        <%= f.submit "Edit", class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<% if current_page?(root_path) %>
    <span><%= pluralize(current_user.microposts.count, "micropost") %></span>
<% elsif current_page?(clips_user_path) %>
    <span><%= pluralize(current_user.clips.count, "clip") %></span>
<% elsif current_page?(albums_user_path) %>
    <span><%= pluralize(current_user.albums.count, "album") %></span>
<% else %>
    <span><%= pluralize(current_user.microposts.count, "micropost") %></span>
<% end %>