config/routes.rb
Rails.application.routes.draw do
  
  get 'taggers/new'

  get 'tags/new'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  get '/signup', to: "users#new"
  
  get "/about", to: "static_pages#about"
  get '/help', to: "static_pages#help"
  get '/contact', to: "static_pages#contact"

  root "static_pages#home"
  
  resources :users do
    member do
      get :clips, :albums
    end
  end
  resources :microposts, only: [:create, :update, :destroy, :edit]
  resources :clips, only: [:create, :update, :edit, :destroy, :show, :new]
  resources :albums, only: [:create, :update, :edit, :destroy, :show, :new]
  resources :affections, only: [:create, :update, :destroy]
  resources :tags, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :taggers, only: [:create, :destroy]
  resources :searches, only: [:new, :show, :create]
  
end

app/models/tag.rb
class Tag < ApplicationRecord
    before_save { self.name=name.downcase }
    has_many :taggers, dependent: :destroy
    has_many :albums, through: :taggers
    validates :name, presence: true, length: {maximum: 15, minimum: 3}, uniqueness: { case_sensitive: false }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]  
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]
  
  def new
    @tag=Tag.new
  end
  
  def create
    @tag=Tag.new(name: params[:tag][:name])
    if @tag.save
      flash[:success]="Tag created"
      redirect_to tags_path
    else
      render "new"
    end
  end
  
  def edit
    @tag=Tag.find(params[:id])
  end
  
  def update
    @tag=Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:success]="tag updated"
      redirect_to tags_path
    else
      render "edit"
    end
  end
  
  def destroy
    Tag.find(params[:id]).destroy
    flash[:success]="tag deleted"
    redirect_to tags_path
  end
  
  def index
    @tags=Tag.all
  end
  
private

  def tag_params
    params.require(:tag).permit(:name)
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_tag.html.erb
<li id="tag-<%= tag.id %>">
    <span class="name"><%= tag.name %></span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(tag.created_at) %> ago.
        <% if current_page?(tags_path) %>
            <% if !current_user.nil? and current_user.admin? %>
                <%= link_to "Delete", tag, method: :delete, data: { confirm: "Are you sure?" } %>
                <%= link_to "Edit", edit_tag_path(tag) %>
            <% end %>
        <% end %>
        <% if !current_user.nil? and current_page?(albums_user_path(current_user)) %>
            <%= form_for(tag.taggers.find_by(album_id: album_to_display), html: {method: :delete}) do |f| %>
                <%= f.submit "remove", class:"btn-danger" %>
            <% end %>
        <% end %>
    </span>
</li>

app/views/tags/edit.html.erb
<% provide(:title, 'edit a tag') %>

<h1>Add a new tag</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@tag) do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            
            <%= f.label :name, "tag name" %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.submit "edit tag", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/tags/index.html.erb
<% provide(:title, "All tags")%>

<h1>All tags</h1>

<ul class="tags">
    <%= render @tags %>
</ul>

app/views/tags/new.html.erb
<% provide(:title, 'Add a tag') %>

<h1>Add a new tag</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@tag) do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            
            <%= f.label :name, "tag name" %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.submit "Add tag", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>