config/routes.rb
Rails.application.routes.draw do
  
  get 'taggers/new'

  get 'tags/new'

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  get '/signup', to: "users#new"
  
  get "/about", to: "static_pages#about"
  get '/help', to: "static_pages#help"
  get '/contact', to: "static_pages#contact"

  root "static_pages#home"
  
  resources :users do
    member do
      get :clips, :albums
    end
  end
  resources :microposts, only: [:create, :update, :destroy, :edit]
  resources :clips, only: [:create, :update, :edit, :destroy, :show, :new]
  resources :albums, only: [:create, :update, :edit, :destroy, :show, :new]
  resources :affections, only: [:create, :update, :destroy]
  resources :tags, only: [:create, :update, :destroy, :new, :edit, :index]
  resources :taggers, only: [:create, :destroy]
  resources :searches, only: [:new, :show, :create]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="#">bejingo</a>
        by <a href="#">Robert</a>.
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a herf="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "bejingo", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", help_path %></li>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Search", new_search_path %></li>
                <% if logged_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "My clips", clips_user_path(current_user) %></li>
                            <li><%= link_to "My albums", albums_user_path(current_user) %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <% if current_user.admin? %>
                                <li><%= link_to "taglist", tags_path %></li>
                                <li><%= link_to "new tag", new_tag_path%></li>
                            <% end %>
                            <li class="divider"></li>
                            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div class="notifications">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type%>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.developement? %>
    </div>
  </body>
</html>